import json, itertools

# Each cluster: id -> list of (word, pos, definition)
CLUSTERS = {
"loquacity": [
    ("loquacious","adj","talking a great deal; very talkative"),
    ("garrulous","adj","excessively talkative, especially about trivial matters"),
    ("voluble","adj","speaking fluently, readily, and at length"),
    ("effusive","adj","expressing feelings or enthusiasm in an unrestrained, over-the-top way"),
    ("gushing","adj","expressing excessive or exaggerated enthusiasm"),
    ("prolix","adj","using far more words than needed; tediously long-winded"),
    ("verbose","adj","using more words than are needed; wordy"),
    ("expansive","adj","becoming openly talkative and unreserved, especially as a conversation warms up"),
    ("chatty","adj","talkative in a friendly, informal way"),
],
"taciturnity": [
    ("taciturn","adj","habitually quiet by temperament; disinclined to speak"),
    ("reticent","adj","not revealing one's thoughts or feelings readily"),
    ("laconic","adj","using very few words; concise to the point of terseness"),
    ("terse","adj","using very few words, often to the point of sounding clipped"),
    ("curt","adj","rudely brief or abrupt in speech"),
    ("succinct","adj","briefly and clearly expressed"),
    ("reserved","adj","slow to reveal emotion, opinions, or personal information"),
    ("uncommunicative","adj","unwilling to talk or share information"),
    ("monosyllabic","adj","(of a person) tending to say very little"),
],
"circuitous": [
    ("circuitous","adj","longer and less direct than a straight path; roundabout"),
    ("convoluted","adj","extremely complex and difficult to follow"),
    ("discursive","adj","moving from topic to topic without a fixed plan"),
    ("rambling","adj","lengthy, wandering, and inconsequential"),
    ("meandering","adj","wandering aimlessly rather than moving directly"),
    ("byzantine","adj","excessively complicated, typically involving many confusing parts"),
    ("labyrinthine","adj","intricate and confusing; like a maze"),
    ("tortuous","adj","full of twists and turns; excessively lengthy and complex"),
    ("circumlocutory","adj","using an indirect, roundabout way of speaking"),
],
"clarity": [
    ("lucid","adj","expressed clearly; easy to understand"),
    ("cogent","adj","clear, logical, and convincing"),
    ("coherent","adj","logical and consistent; easy to follow"),
    ("articulate","adj","able to express oneself fluently and clearly"),
    ("pellucid","adj","translucently clear in style or meaning"),
    ("perspicuous","adj","clearly expressed and easily understood"),
    ("trenchant","adj","forceful and penetrating in expression or thought"),
    ("incisive","adj","intelligently sharp and clear in analysis or expression"),
],
"obscurity": [
    ("ambiguous","adj","open to more than one interpretation; unclear"),
    ("equivocal","adj","open to two or more interpretations; deliberately vague"),
    ("cryptic","adj","having a puzzling, hidden meaning that requires interpretation"),
    ("opaque","adj","hard to understand; not transparent"),
    ("obscure","adj","not clearly expressed or easily understood"),
    ("esoteric","adj","understood by only a small number of people with special knowledge"),
    ("arcane","adj","understood by very few; mysterious or secret"),
    ("abstruse","adj","difficult to understand because of its abstract complexity"),
    ("enigmatic","adj","difficult to interpret or understand; mysterious"),
    ("nebulous","adj","unclear, vague, or ill-defined"),
],
"flattery": [
    ("sycophantic","adj","behaving obsequiously toward someone to gain advantage"),
    ("obsequious","adj","excessively eager to please or obey, often servilely so"),
    ("fawning","adj","seeking approval through excessive attention and compliments"),
    ("servile","adj","excessively willing to serve or please others"),
    ("ingratiating","adj","attempting to gain favor through deliberately pleasant behavior"),
    ("adulation","noun","excessive admiration or praise"),
    ("unctuous","adj","smoothly and excessively complimentary in a way that feels insincere"),
    ("toady","noun","a person who flatters someone important for personal gain"),
    ("flattery","noun","excessive and often insincere praise or compliments"),
    ("blandishment","noun","a smooth, coaxing compliment meant to win someone over"),
    ("sycophancy","noun","excessive, self-serving deference shown toward someone with power or influence"),
],
"criticism": [
    ("admonish","verb","warn or reprimand someone firmly"),
    ("rebuke","verb","express sharp disapproval or criticism"),
    ("reprove","verb","express disapproval of; criticize mildly"),
    ("castigate","verb","reprimand someone severely"),
    ("chastise","verb","scold or reprimand someone harshly, especially for wrongdoing"),
    ("excoriate","verb","criticize someone severely and harshly"),
    ("vilify","verb","speak or write about someone in an abusively disparaging way"),
    ("disparage","verb","regard or describe as being of little worth"),
    ("deride","verb","express contempt for; ridicule"),
    ("denounce","verb","publicly declare to be wrong or evil"),
],
"praise": [
    ("laud","verb","praise highly"),
    ("extol","verb","praise enthusiastically"),
    ("eulogize","verb","praise highly, especially in a formal speech or piece of writing"),
    ("commend","verb","praise formally or officially"),
    ("venerate","verb","regard with great respect; revere"),
    ("acclaim","verb","praise enthusiastically and publicly"),
    ("exalt","verb","praise highly; elevate in rank or status"),
    ("encomium","noun","a formal expression of high praise"),
    ("panegyric","noun","a formal speech or piece of writing praising someone highly"),
    ("tribute","noun","an act, statement, or gift intended to show gratitude or admiration"),
    ("accolade","noun","an award or expression of praise for an achievement"),
    ("plaudit","noun","an expression of praise or approval, especially for an achievement"),
],
"mockery": [
    ("sardonic","adj","grimly mocking or cynical"),
    ("sarcastic","adj","using irony to mock or convey contempt"),
    ("caustic","adj","bitterly cutting in a way that stings, like a corrosive acid"),
    ("mordant","adj","sharply critical, often with a dark, biting wit"),
    ("derisive","adj","expressing contempt or ridicule"),
    ("scathing","adj","witheringly harsh and critical"),
    ("satirical","adj","using humor, irony, or exaggeration to criticize"),
    ("facetious","adj","treating serious issues with inappropriate humor"),
    ("flippant","adj","not showing a serious or respectful attitude"),
    ("glib","adj","fluent and voluble but insincere or superficial"),
],
"stubbornness": [
    ("obstinate","adj","stubbornly refusing to change one's opinion"),
    ("intransigent","adj","unwilling to change one's views or come to an agreement"),
    ("recalcitrant","adj","having an obstinately uncooperative attitude"),
    ("obdurate","adj","stubbornly refusing to change one's mind"),
    ("adamant","adj","refusing to be persuaded; firmly resolved"),
    ("inflexible","adj","unwilling to change or compromise"),
    ("unyielding","adj","not giving way; firm"),
    ("headstrong","adj","determined to act on one's own will, ignoring advice"),
],
"persistence": [
    ("tenacious","adj","persisting firmly; not readily letting go"),
    ("resolute","adj","admirably purposeful and determined"),
    ("steadfast","adj","resolutely or dutifully firm and unwavering"),
    ("indefatigable","adj","persisting tirelessly; never tiring"),
    ("dogged","adj","persistent and determined"),
    ("assiduous","adj","showing great care, attention, and perseverance"),
    ("diligent","adj","showing care and conscientious effort"),
    ("sedulous","adj","persistently and carefully industrious in one's efforts"),
],
"flexibility": [
    ("malleable","adj","easily influenced or shaped"),
    ("adaptable","adj","able to adjust readily to new conditions"),
    ("versatile","adj","able to adapt to many different functions"),
    ("pliable","adj","easily bent or influenced"),
    ("amenable","adj","open and responsive to suggestion"),
    ("accommodating","adj","willing to fulfill others' wishes"),
    ("tractable","adj","easy to control or influence"),
],
"changeability": [
    ("capricious","adj","given to sudden, unaccountable changes of mood or behavior"),
    ("mercurial","adj","subject to sudden or unpredictable changes"),
    ("fickle","adj","changing frequently, especially in loyalties"),
    ("volatile","adj","liable to change rapidly and unpredictably"),
    ("erratic","adj","not consistent or regular in pattern"),
    ("whimsical","adj","playfully quaint or fanciful, especially unpredictably so"),
    ("vacillating","adj","wavering between different opinions or actions"),
    ("inconstant","adj","frequently changing; not faithful or steady"),
],
"calm": [
    ("placid","adj","not easily upset or excited; calm"),
    ("serene","adj","calm, peaceful, and untroubled"),
    ("tranquil","adj","free from disturbance; calm"),
    ("unflappable","adj","not easily upset or excited"),
    ("equanimous","adj","having equanimity; calm and composed, especially under pressure"),
    ("stoic","adj","enduring pain or hardship without showing feelings"),
    ("imperturbable","adj","unable to be upset or excited; calm"),
    ("phlegmatic","adj","having an unemotional, stolidly calm disposition"),
],
"anxious": [
    ("apprehensive","adj","anxious or fearful about the future"),
    ("trepidation","noun","a feeling of fear or anxiety about something that may happen"),
    ("diffident","adj","modest or shy due to a lack of self-confidence"),
    ("timorous","adj","showing or suffering from nervousness; timid"),
    ("perturbed","adj","anxious or unsettled"),
    ("agitated","adj","troubled, disturbed, or nervous"),
    ("jittery","adj","nervous; unable to relax"),
    ("skittish","adj","nervous and easily frightened"),
],
"angry": [
    ("irate","adj","feeling or characterized by great anger"),
    ("indignant","adj","feeling or showing anger at perceived unfair treatment"),
    ("livid","adj","furiously angry"),
    ("irascible","adj","having a tendency to be easily angered"),
    ("choleric","adj","bad-tempered; irritable"),
    ("splenetic","adj","bad-tempered; spiteful"),
    ("vitriolic","adj","filled with bitter criticism or malice"),
    ("acrimonious","adj","bitter and angry, especially in tone"),
    ("belligerent","adj","hostile and aggressive"),
    ("bellicose","adj","demonstrating aggression and eagerness to fight"),
],
"friendly": [
    ("amiable","adj","having a friendly and pleasant manner"),
    ("congenial","adj","pleasant because of a personality similar to one's own"),
    ("affable","adj","friendly, good-natured, and easy to talk to"),
    ("gregarious","adj","fond of company; sociable"),
    ("convivial","adj","friendly, lively, and enjoyable"),
    ("cordial","adj","warm and friendly"),
    ("genial","adj","friendly and cheerful"),
],
"unfriendly": [
    ("aloof","adj","not friendly or forthcoming; distant"),
    ("reclusive","adj","avoiding the company of others; solitary"),
    ("misanthropic","adj","disliking humankind"),
    ("churlish","adj","rude in a mean-spirited way"),
    ("surly","adj","bad-tempered and unfriendly"),
    ("curmudgeonly","adj","bad-tempered, especially in an older person"),
    ("standoffish","adj","cold or distant in manner"),
    ("brusque","adj","abrupt or curt in speech or manner"),
],
"generous": [
    ("munificent","adj","extremely generous"),
    ("magnanimous","adj","generous or forgiving, especially toward a rival"),
    ("philanthropic","adj","seeking to promote the welfare of others; generous"),
    ("altruistic","adj","showing selfless concern for the well-being of others"),
    ("benevolent","adj","well-meaning and kindly"),
    ("charitable","adj","generous in giving to those in need"),
    ("unstinting","adj","given or giving generously and without restraint"),
],
"stingy": [
    ("avaricious","adj","having an extreme greed for wealth"),
    ("miserly","adj","extremely unwilling to spend money"),
    ("parsimonious","adj","stingy to the point of being unwilling to spend even a little"),
    ("covetous","adj","having a strong desire for something owned by another"),
    ("rapacious","adj","aggressively greedy or grasping"),
    ("venal","adj","showing a willingness to be bribed; corruptible"),
    ("mercenary","adj","motivated primarily by a desire for money"),
    ("frugal","adj","sparing or economical with money or resources"),
],
"honest": [
    ("candid","adj","truthful and straightforward, even when it's unflattering"),
    ("forthright","adj","direct and outspoken"),
    ("guileless","adj","innocent and without deception"),
    ("ingenuous","adj","openly innocent and unsuspecting, without any guile"),
    ("veracious","adj","speaking or representing the truth; truthful"),
    ("artless","adj","without cunning or deceit; natural and simple"),
    ("frank","adj","open, honest, and direct in speech"),
],
"deceitful": [
    ("duplicitous","adj","deceitful; given to double-dealing"),
    ("disingenuous","adj","not candid; giving a false impression of sincerity"),
    ("surreptitious","adj","kept secret, especially because it would not be approved of"),
    ("devious","adj","showing skill in achieving one's ends by indirect or deceitful methods"),
    ("furtive","adj","attempting to avoid notice, typically because of guilt"),
    ("cunning","adj","skilled in achieving one's ends through deceit"),
    ("wily","adj","skilled at gaining an advantage through deceit"),
    ("guile","noun","crafty, calculated behavior used to trick or manipulate people"),
    ("machiavellian","adj","willing to use scheming or unscrupulous means to gain power"),
],
"arrogant": [
    ("haughty","adj","arrogantly superior and disdainful"),
    ("pompous","adj","affectedly grand or self-important"),
    ("imperious","adj","assuming power or authority without justification; domineering"),
    ("supercilious","adj","behaving as if superior to others; disdainful"),
    ("condescending","adj","showing an attitude of superiority toward others"),
    ("pretentious","adj","attempting to impress by affecting greater importance than one has"),
    ("grandiose","adj","impressive or affectedly grand"),
    ("vainglorious","adj","excessively proud of oneself; boastful"),
],
"humble": [
    ("modest","adj","having a moderate estimation of one's own abilities or achievements"),
    ("unassuming","adj","not pretentious or showy; keeping a low profile"),
    ("unpretentious","adj","plain and simple; making no attempt to impress others"),
    ("demure","adj","reserved and shy in a quiet, decorous manner"),
    ("meek","adj","quiet, gentle, and submissive; humble in spirit"),
    ("self-effacing","adj","deliberately playing down one's own importance or achievements"),
    ("unobtrusive","adj","not conspicuous or attracting attention"),
],
"bold": [
    ("audacious","adj","showing a willingness to take bold risks"),
    ("intrepid","adj","fearless; adventurous"),
    ("valiant","adj","possessing or showing courage"),
    ("dauntless","adj","showing fearlessness and determination"),
    ("indomitable","adj","impossible to subdue or defeat"),
    ("brazen","adj","bold and without shame"),
    ("gallant","adj","brave, especially in a courteous, chivalrous way"),
    ("plucky","adj","having courage and determination"),
],
"cowardly": [
    ("craven","adj","contemptibly lacking in courage"),
    ("pusillanimous","adj","showing a shameful lack of courage or resolve"),
    ("faint-hearted","adj","lacking courage or resolution"),
    ("cowering","adj","crouching or shrinking back in fear"),
    ("spineless","adj","lacking courage or determination"),
    ("mousy","adj","meek and unassertive in a quiet, retiring way"),
    ("timid","adj","showing a lack of courage or confidence"),
],
"lazy": [
    ("indolent","adj","wanting to avoid activity or exertion; lazy"),
    ("lethargic","adj","sluggish and lacking energy or enthusiasm"),
    ("languid","adj","displaying a disinclination for physical exertion; slow"),
    ("torpid","adj","sluggish and mentally slow, as if half-asleep"),
    ("listless","adj","lacking energy or enthusiasm"),
    ("slothful","adj","lazy; disinclined to activity or exertion"),
    ("lackadaisical","adj","lacking enthusiasm and thoroughness; carelessly lazy"),
    ("somnolent","adj","sleepy; drowsy"),
],
"energetic": [
    ("vigorous","adj","strong, healthy, and full of energy"),
    ("industrious","adj","diligent and hard-working"),
    ("dynamic","adj","characterized by constant, productive activity or change"),
    ("zealous","adj","having or showing great energy and enthusiasm"),
    ("ebullient","adj","cheerful and full of energy"),
    ("exuberant","adj","full of energy, excitement, and enthusiasm"),
    ("animated","adj","full of life or excitement"),
    ("spirited","adj","full of energy, enthusiasm, and determination"),
],
"skeptical": [
    ("skeptical","adj","not easily convinced; having doubts"),
    ("dubious","adj","hesitating or doubting"),
    ("incredulous","adj","unwilling or unable to believe something"),
    ("wary","adj","feeling or showing caution about possible dangers"),
    ("suspicious","adj","having or showing a cautious distrust of someone"),
    ("distrustful","adj","inclined to doubt someone's honesty"),
    ("cynical","adj","believing that people are motivated mainly by self-interest"),
],
"gullible": [
    ("gullible","adj","easily persuaded to believe something; easily deceived"),
    ("credulous","adj","too ready to believe things; easily convinced"),
    ("naive","adj","showing a lack of experience or sophistication"),
    ("unsuspecting","adj","not aware of or alert to any danger or deception"),
    ("trusting","adj","inclined to believe others are honest or reliable"),
    ("unwary","adj","not cautious; easily deceived"),
],
"wise": [
    ("sagacious","adj","having or showing keen judgment; wise"),
    ("astute","adj","having a sharp, accurate judgment of people and situations"),
    ("perspicacious","adj","having a keen mental sharpness that sees past surface appearances"),
    ("discerning","adj","showing good judgment, especially about people or art"),
    ("judicious","adj","having, showing, or done with good judgment; sensible"),
    ("prudent","adj","acting with care and thought for the future"),
    ("shrewd","adj","showing practical cleverness, especially in business or dealings"),
    ("perceptive","adj","having keen insight or intuition"),
],
"foolish": [
    ("fatuous","adj","silly and pointless"),
    ("inane","adj","silly; lacking sense or substance"),
    ("asinine","adj","extremely foolish or stupid"),
    ("puerile","adj","childishly silly and trivial"),
    ("imprudent","adj","not showing care for the consequences; rash"),
    ("injudicious","adj","showing poor judgment; unwise"),
    ("obtuse","adj","annoyingly insensitive or slow to understand"),
],
"cheerful": [
    ("buoyant","adj","cheerful and optimistic"),
    ("jovial","adj","cheerful and friendly"),
    ("jubilant","adj","feeling or expressing great happiness and triumph"),
    ("sanguine","adj","optimistic or positive, especially in a difficult situation"),
    ("exultant","adj","triumphantly happy"),
    ("effervescent","adj","vivacious, enthusiastic, and bubbly"),
    ("elated","adj","extremely happy and excited"),
],
"gloomy": [
    ("morose","adj","sullen and ill-tempered"),
    ("somber","adj","dark, dull, or gravely serious in mood"),
    ("melancholic","adj","sad and thoughtful; given to sadness"),
    ("lugubrious","adj","looking or sounding sad and dismal"),
    ("doleful","adj","expressing sorrow; mournful"),
    ("dour","adj","relentlessly severe, stern, or gloomy"),
    ("despondent","adj","in low spirits from loss of hope or courage"),
    ("forlorn","adj","pitifully sad and abandoned or lonely"),
],
"impartial": [
    ("impartial","adj","treating all rivals or disputants equally; fair"),
    ("unbiased","adj","showing no prejudice; fair"),
    ("objective","adj","not influenced by personal feelings; fair"),
    ("equitable","adj","fair to all parties, especially in the just distribution of something"),
    ("dispassionate","adj","not influenced by strong emotion; rational and calm"),
    ("neutral","adj","not aligned with or supporting any side"),
    ("even-handed","adj","treating everyone the same way, without favoring one side"),
],
"biased": [
    ("partisan","adj","strongly favoring one party or cause over others"),
    ("tendentious","adj","expressing a strong, biased point of view"),
    ("prejudiced","adj","having a preconceived opinion not based on reason"),
    ("one-sided","adj","favoring one side excessively; biased"),
    ("bigoted","adj","obstinately and unreasonably attached to a belief or view"),
    ("parochial","adj","having a limited or narrow outlook or scope"),
],
"secretive": [
    ("clandestine","adj","done secretively, especially because illicit"),
    ("covert","adj","not openly acknowledged or displayed; secret"),
    ("stealthy","adj","cautious and surreptitious in action"),
    ("veiled","adj","partially disguised or concealed"),
    ("undercover","adj","done or working secretly"),
    ("underhanded","adj","acting in a secret or dishonest way"),
    ("secretive","adj","inclined to conceal feelings, activities, or information"),
],
"open": [
    ("transparent","adj","easy to perceive or detect; open and honest"),
    ("forthcoming","adj","willing to give information; open"),
    ("overt","adj","done or shown openly; not secret"),
    ("unreserved","adj","without reservations; completely open and frank"),
    ("outspoken","adj","direct and forthright in speech"),
    ("plainspoken","adj","speaking in a simple, direct way"),
],
"abundant": [
    ("plethora","noun","a large or excessive amount of something"),
    ("myriad","adj","a countless or extremely great number of"),
    ("copious","adj","present in large amounts; plentiful and generous in supply"),
    ("abundant","adj","existing in large quantities; plentiful"),
    ("profuse","adj","given or occurring in overflowing amounts, often to excess"),
    ("prolific","adj","producing a large output or number of something, especially works"),
    ("teeming","adj","full of or swarming with something"),
],
"scarce": [
    ("scarce","adj","insufficient for demand; rare"),
    ("sparse","adj","thinly dispersed or scattered"),
    ("meager","adj","lacking in quantity or quality"),
    ("paucity","noun","the presence of something in only small or insufficient quantities"),
    ("dearth","noun","a situation where too little of something is available"),
    ("scant","adj","only just enough, or not quite enough"),
    ("spartan","adj","simple and severe, without comfort or luxury"),
    ("shortage","noun","a state in which something is not available in sufficient amounts"),
    ("insufficiency","noun","a lack of adequate amount, ability, or quality"),
    ("scarcity","noun","the condition of not having enough of something to meet demand"),
],
"excessive": [
    ("superfluous","adj","unnecessary, especially through being more than enough"),
    ("extraneous","adj","irrelevant or unnecessary"),
    ("gratuitous","adj","uncalled for; lacking good reason; unnecessary"),
    ("redundant","adj","no longer needed because it repeats what is already there"),
    ("excessive","adj","more than is necessary or desirable"),
    ("surplus","adj","an amount left over when requirements have been met"),
    ("inordinate","adj","far beyond what is normal, reasonable, or necessary"),
],
"moderate": [
    ("abstemious","adj","not self-indulgent, especially in eating and drinking"),
    ("temperate","adj","showing moderation or self-restraint"),
    ("austere","adj","severe or strict in manner; plain and self-denying"),
    ("ascetic","adj","characterized by severe self-discipline and avoidance of indulgence"),
    ("restrained","adj","kept under control; not extreme"),
    ("moderate","adj","average in amount, intensity, or degree; not extreme"),
    ("sober","adj","serious and level-headed, without exaggeration or excess"),
],
"submissive": [
    ("docile","adj","ready to accept control or instruction; submissive"),
    ("compliant","adj","inclined to agree with others or obey rules"),
    ("acquiescent","adj","ready to accept something without protest"),
    ("deferential","adj","showing respect for someone or something"),
    ("pliant","adj","easily influenced or bent to another's will"),
    ("subservient","adj","prepared to obey others unquestioningly"),
    ("yielding","adj","tending to give way under pressure rather than resist"),
],
"rebellious": [
    ("defiant","adj","showing defiance; boldly resistant to authority"),
    ("insubordinate","adj","disobedient to authority"),
    ("refractory","adj","stubborn or unmanageable; resistant to discipline"),
    ("mutinous","adj","refusing to obey orders; rebellious"),
    ("contumacious","adj","stubbornly or willfully disobedient to authority"),
    ("unruly","adj","disorderly and disruptive; not amenable to discipline"),
    ("insurgent","adj","rising in active revolt"),
],
"harmful": [
    ("deleterious","adj","causing harm or damage"),
    ("pernicious","adj","having a harmful effect, especially in a gradual way"),
    ("noxious","adj","harmful, poisonous, or very unpleasant"),
    ("detrimental","adj","tending to cause harm"),
    ("malignant","adj","harmful in intention or effect; malicious"),
    ("injurious","adj","causing or likely to cause damage or harm"),
    ("virulent","adj","bitterly hostile or severe; extremely harmful"),
],
"beneficial": [
    ("beneficial","adj","producing a good or helpful result"),
    ("salutary","adj","having a good effect, often despite seeming harsh at first"),
    ("efficacious","adj","effective in producing a desired result"),
    ("propitious","adj","favorable; giving a good chance of success"),
    ("auspicious","adj","conducive to success; favorable"),
    ("advantageous","adj","providing a favorable edge or benefit toward a purpose"),
    ("felicitous","adj","well-chosen, apt, or fortunate"),
],
"rhetorical_devices": [
    ("hyperbole","noun","exaggerated statements not meant to be taken literally"),
    ("euphemism","noun","a mild or indirect word substituted for a harsh or blunt one"),
    ("oxymoron","noun","a figure of speech combining contradictory terms"),
    ("allegory","noun","a story, poem, or picture with a hidden symbolic meaning"),
    ("motif","noun","a recurring element or theme in a work"),
    ("paradox","noun","a statement that seems contradictory but may be true"),
    ("juxtaposition","noun","the fact of placing two things close together for contrasting effect"),
    ("irony","noun","the expression of meaning using language that signifies the opposite"),
    ("understatement","noun","the presentation of something as smaller or less important than it is"),
    ("allusion","noun","an indirect reference to something"),
],
"evidence_reasoning": [
    ("empirical","adj","based on observation or experience rather than theory"),
    ("hypothesis","noun","a proposed explanation made on limited evidence, as a starting point"),
    ("corroborate","verb","confirm or give support to a statement or finding"),
    ("refute","verb","prove a statement or theory to be wrong"),
    ("substantiate","verb","provide evidence to support or prove the truth of"),
    ("conjecture","noun","an opinion or conclusion formed on the basis of incomplete information"),
    ("extrapolate","verb","extend a conclusion to an assumed, similar situation"),
    ("anecdotal","adj","based on personal accounts rather than facts or research"),
    ("fallacious","adj","based on a mistaken belief; containing a flaw in reasoning"),
    ("specious","adj","seeming reasonable or true, but actually false or misleading"),
    ("dichotomy","noun","a division or contrast between two things that are opposed"),
    ("plausible","adj","seeming reasonable or probable"),
    ("postulate","noun","a thing suggested or assumed as true as the basis for reasoning"),
    ("premise","noun","a previous statement from which another is inferred or follows logically"),
    ("validate","verb","check or prove that something is accurate or justified"),
    ("verify","verb","make sure or demonstrate that something is true or accurate"),
],
"temporary": [
    ("ephemeral","adj","lasting for only a brief time before disappearing"),
    ("transient","adj","staying or lasting only a short time before moving on or changing"),
    ("fleeting","adj","lasting for just a moment; gone almost as soon as it appears"),
    ("evanescent","adj","soon passing out of sight; quickly fading"),
    ("transitory","adj","existing or valid for only a limited time before ending"),
    ("momentary","adj","lasting for only a single moment; very brief"),
    ("impermanent","adj","not lasting forever; bound to end or change eventually"),
],
"permanent": [
    ("perpetual","adj","never ending or changing"),
    ("enduring","adj","lasting over a long period of time"),
    ("indelible","adj","unable to be forgotten or removed; permanent"),
    ("immutable","adj","unchanging over time; unable to be changed"),
    ("perennial","adj","lasting or existing for a long time; recurring"),
    ("everlasting","adj","lasting forever, or for a very long time"),
    ("abiding","adj","continuing steadily without fading over time"),
],
"old_fashioned": [
    ("hackneyed","adj","overused and no longer having force or novelty; clichéd"),
    ("trite","adj","overused and of little interest; unoriginal"),
    ("banal","adj","so lacking in originality as to be obvious and boring"),
    ("cliched","adj","overused and stereotyped; lacking originality"),
    ("archaic","adj","old-fashioned or no longer in ordinary use"),
    ("antiquated","adj","old-fashioned or outdated"),
    ("obsolete","adj","no longer produced or used; out of date"),
    ("anachronistic","adj","belonging to a period other than the one portrayed; out of place in time"),
],
"original": [
    ("novel","adj","new or unusual in an interesting way"),
    ("innovative","adj","introducing new ideas; original and creative"),
    ("unprecedented","adj","never done or known before"),
    ("groundbreaking","adj","introducing an entirely new approach that others will follow"),
    ("avant-garde","adj","new and experimental, especially in art or ideas"),
    ("unorthodox","adj","contrary to what is usual or traditional"),
],
"practical": [
    ("pragmatic","adj","dealing with things sensibly and realistically"),
    ("utilitarian","adj","designed to be useful rather than attractive; practical"),
    ("expedient","adj","convenient and practical, although possibly improper"),
    ("practicable","adj","able to be done or put into practice successfully"),
    ("hardheaded","adj","practical and realistic; not sentimental"),
],
"idealistic": [
    ("idealistic","adj","believing that a perfect situation can be achieved; unrealistic"),
    ("quixotic","adj","pursuing lofty, impossible goals with naive enthusiasm"),
    ("utopian","adj","envisioning a perfect society that could never really exist"),
    ("starry-eyed","adj","filled with naive hope and optimism about how things will turn out"),
    ("impractical","adj","not adapted for actual use; unrealistic"),
],
"dull": [
    ("mundane","adj","lacking interest or excitement; dull"),
    ("monotonous","adj","repeating in a flat, unvarying pattern until it becomes wearisome"),
    ("tedious","adj","too long, slow, or dull; tiresome"),
    ("insipid","adj","lacking vigor, flavor, or interest; bland"),
    ("humdrum","adj","lacking excitement or variety; dull"),
    ("prosaic","adj","lacking imagination; dull and ordinary"),
    ("vapid","adj","offering nothing that is stimulating or challenging; dull"),
],
"curious": [
    ("inquisitive","adj","curious or given to inquiry; eager for knowledge"),
    ("inquiring","adj","interested in learning about many different things"),
    ("probing","adj","searching or exploring thoroughly"),
    ("avid","adj","having or showing a keen interest in or enthusiasm for something"),
    ("nosy","adj","overly curious about other people's affairs"),
    ("prying","adj","actively digging into others' private business in an unwelcome way"),
],
"indifferent": [
    ("apathetic","adj","showing or feeling no interest, enthusiasm, or concern"),
    ("indifferent","adj","having no particular interest or sympathy; unconcerned"),
    ("impassive","adj","not feeling or showing emotion"),
    ("detached","adj","not influenced by or involved with something; aloof"),
    ("blase","adj","unimpressed by something because of over-exposure to it"),
    ("unmoved","adj","not affected emotionally"),
],
"peak_trough": [
    ("zenith","noun","the highest point reached; the peak"),
    ("nadir","noun","the lowest point"),
    ("apex","noun","the top or highest point of something"),
    ("pinnacle","noun","the most successful point; the peak"),
    ("culmination","noun","the highest or climactic point of something, especially as attained after a long time"),
    ("acme","noun","the point at which someone or something is best, most successful, or most skilled"),
],
"puzzle_dilemma": [
    ("quandary","noun","a state of confusion over which of several options to choose"),
    ("conundrum","noun","a confusing and difficult problem or question"),
    ("predicament","noun","a difficult, unpleasant, or embarrassing situation"),
    ("dilemma","noun","a situation requiring a choice between equally undesirable options"),
    ("impasse","noun","a situation with no way out; a deadlock"),
    ("quagmire","noun","a difficult, precarious, or entrapping situation"),
],
"sign_omen": [
    ("harbinger","noun","a person or thing that announces or signals the approach of something"),
    ("precursor","noun","a person or thing that comes before another of the same kind; a forerunner"),
    ("omen","noun","an event thought to foretell whether something good or bad will happen"),
    ("portent","noun","a sign or warning that something momentous is about to happen"),
    ("foreshadowing","noun","a warning or indication of a future event"),
    ("augury","noun","a sign believed to predict how a future event will turn out"),
],
"remnant_trace": [
    ("vestige","noun","a small trace left behind of something that has otherwise vanished"),
    ("remnant","noun","a small remaining quantity of something"),
    ("relic","noun","an object or custom that has survived from an earlier period"),
    ("residue","noun","a small amount of something that remains after the main part has gone"),
    ("holdover","noun","a person or thing that remains from an earlier time"),
],
"catalyst": [
    ("catalyst","noun","a person or thing that precipitates an event or change"),
    ("impetus","noun","the force or energy that makes something happen or happen faster"),
    ("stimulus","noun","something that rouses activity or energy; an incentive"),
    ("instigator","noun","a person who initiates an action or event"),
    ("linchpin","noun","a person or thing vital to an enterprise or organization"),
],
"paragon": [
    ("paragon","noun","a person or thing regarded as a perfect example of a particular quality"),
    ("epitome","noun","a perfect example of a particular quality or type"),
    ("quintessence","noun","the most perfect or typical embodiment of a quality or class"),
    ("exemplar","noun","a person or thing serving as a typical example or model"),
    ("archetype","noun","a typical example of a person or thing; the original model"),
],
"boon_bane": [
    ("boon","noun","a thing that is helpful or beneficial"),
    ("bane","noun","a cause of great distress or annoyance"),
    ("scourge","noun","a person or thing that causes great trouble or suffering"),
    ("affliction","noun","something that causes pain or suffering"),
    ("windfall","noun","an unexpected, unearned stroke of good fortune"),
],
"anomaly": [
    ("anomaly","noun","something that deviates from what is standard or expected"),
    ("aberration","noun","a departure from what is normal, usual, or expected"),
    ("deviation","noun","an act of departing from an established course or norm"),
    ("irregularity","noun","a state, event, or practice not in accordance with rules or convention"),
    ("outlier","noun","a thing situated away from the main body; something atypical"),
],
"surrender": [
    ("capitulate","verb","surrender or give in to a demand"),
    ("succumb","verb","fail to resist pressure, temptation, or other negative force; give way"),
    ("relinquish","verb","voluntarily cease to keep or claim; give up"),
    ("concede","verb","admit that something is true after first denying it; give up a point"),
    ("abdicate","verb","fail to fulfil a duty or responsibility; formally give up power"),
],
}

RELATED = {
"loquacity": ["taciturnity"],
"taciturnity": ["loquacity"],
"circuitous": ["clarity"],
"clarity": ["obscurity","circuitous"],
"obscurity": ["clarity"],
"flattery": ["criticism"],
"criticism": ["praise","flattery"],
"praise": ["criticism","mockery"],
"mockery": ["praise"],
"stubbornness": ["flexibility"],
"flexibility": ["stubbornness","submissive"],
"persistence": ["lazy"],
"changeability": ["persistence"],
"calm": ["anxious","angry"],
"anxious": ["calm"],
"angry": ["calm"],
"friendly": ["unfriendly"],
"unfriendly": ["friendly"],
"generous": ["stingy"],
"stingy": ["generous"],
"honest": ["deceitful"],
"deceitful": ["honest"],
"arrogant": ["humble"],
"humble": ["arrogant"],
"bold": ["cowardly"],
"cowardly": ["bold"],
"lazy": ["energetic"],
"energetic": ["lazy"],
"skeptical": ["gullible"],
"gullible": ["skeptical"],
"wise": ["foolish"],
"foolish": ["wise","dull"],
"cheerful": ["gloomy"],
"gloomy": ["cheerful"],
"impartial": ["biased"],
"biased": ["impartial"],
"secretive": ["open"],
"open": ["secretive","honest"],
"abundant": ["scarce"],
"scarce": ["abundant"],
"excessive": ["moderate"],
"moderate": ["excessive"],
"submissive": ["rebellious"],
"rebellious": ["submissive","stubbornness"],
"harmful": ["beneficial"],
"beneficial": ["harmful"],
"rhetorical_devices": ["evidence_reasoning"],
"evidence_reasoning": ["rhetorical_devices"],
"temporary": ["permanent"],
"permanent": ["temporary"],
"old_fashioned": ["original"],
"original": ["old_fashioned"],
"practical": ["idealistic"],
"idealistic": ["practical"],
"dull": ["indifferent","foolish"],
"curious": ["indifferent"],
"indifferent": ["dull","curious"],
"peak_trough": ["puzzle_dilemma","anomaly"],
"puzzle_dilemma": ["peak_trough","anomaly"],
"sign_omen": ["catalyst","anomaly"],
"remnant_trace": ["anomaly","boon_bane"],
"catalyst": ["sign_omen","paragon"],
"paragon": ["catalyst","boon_bane"],
"boon_bane": ["remnant_trace","paragon"],
"anomaly": ["peak_trough","puzzle_dilemma"],
"surrender": ["submissive","rebellious"],
}

# Build word entries
entries = []
seen_words = set()
idx = 0
for cluster, items in CLUSTERS.items():
    for word, pos, definition in items:
        key = word.lower()
        if key in seen_words:
            raise ValueError(f"duplicate word: {word}")
        seen_words.add(key)
        entries.append({
            "id": idx,
            "word": word,
            "pos": pos,
            "def": definition,
            "cluster": cluster,
        })
        idx += 1

# cluster -> list of entry ids
cluster_ids = {}
for e in entries:
    cluster_ids.setdefault(e["cluster"], []).append(e["id"])

# Two separate tiers so the client can prefer true same-cluster near-synonyms
# before ever reaching into a related (often near-antonym) cluster:
#   "same"    = other words in this word's own cluster (tight synonym neighborhood)
#   "related" = words in linked clusters only (used as a fallback, not mixed in by default)
for e in entries:
    same = set(cluster_ids[e["cluster"]])
    same.discard(e["id"])
    related = set()
    for rc in RELATED.get(e["cluster"], []):
        related.update(cluster_ids.get(rc, []))
    related -= same
    related.discard(e["id"])
    e["same"] = sorted(same)
    e["related"] = sorted(related)

# validation: same-cluster tier alone should cover most words; combined should always cover 4
bad = [e for e in entries if len(e["same"]) + len(e["related"]) < 4]
thin = [e for e in entries if len(e["same"]) < 4]
print("total words:", len(entries))
print("total clusters:", len(CLUSTERS))
print("entries needing related-cluster fallback (same-cluster pool < 4):", len(thin))
print("entries with combined pool < 4 (would need global fallback):", len(bad))
for e in bad:
    print("  LOW POOL:", e["word"], e["cluster"], len(e["same"]), len(e["related"]))

with open("/home/claude/words_data.json", "w") as f:
    json.dump(entries, f, indent=0)

print("wrote words_data.json")
